### ISSUE TITLE
Searching for tracks

### ISSUE THREAD

**Issue by ghost** [doctorpiorno/jammming#2]
https://github.com/doctorpiorno/jammming/blob/master/src/Components/App/App.js#L49-L54

Nice job remembering that the `Spotify.search()` method returns a `Promise` and properly chaining a `.then()` before setting your state 👍 

Consider renaming the `result` parameter to `foundTracks` so that you can use ES6's property/value shorthand syntax here:

```javascript
this.setState({ foundTracks });
```

You can use this whenever you need an object whose key is the same its value (i.e. `{ searchResults: searchResults }` ) and you might find it makes your code more terse.

**Comment by doctorpiorno** [comment]
Thanks for the feedback.
