### ISSUE TITLE
Adding tracks to playlist

### ISSUE THREAD

**Issue by ghost** [doctorpiorno/jammming#3]
https://github.com/doctorpiorno/jammming/blob/master/src/Components/App/App.js#L63-L76

Consider using `.find()` or `.some()` to determine if a track ID exists in the current playlist before adding it in.  

Iterator methods can make it easier for you to write terse and expressive code. This is much better than relying on the traditional loop. Also, consider breaking out of the forEach loop once the track is found. There's no need to continue searching once you've found the track exists, is there?

Good job using `.concat()`, but your reasoning is wrong. You can pass `.concat()` a track object and it will still a return a single new array with the track object added to the end of it. Wrapping the track object inside of an array is "extra".

**Comment by doctorpiorno** [comment]
Thanks for the feedback. I was faintly aware that using a loop to determine if a track ID exists in the playlist was a bit of a brute force approach.But that was my first thought and I wanted to see if it worked, so I left it in.  :)

Thanks also for the note re: concat. I eventually figured out my fears of the array being overwritten were unfounded, but that was after the submission.
