### ISSUE TITLE
Avoid mutating state

### ISSUE THREAD

**Issue by ghost** [doctorpiorno/jammming#4]
https://github.com/doctorpiorno/jammming/blob/master/src/Components/App/App.js#L63-L86

When you write some code like

```javascript
let someArray = this.state.someProperty;
someArray.push();
```

You are directly mutating React's state, which is considered a bad practice. 

Nice job using non-mutating `Array` methods instead, like `slice`, `concat`, `map`, or `filter` which all return a brand new array instead. You are then free to mutate _that_ copied array and then pass the final version of that copied array to `this.setState()`.

Read more about [immutability in React here](https://medium.com/pro-react/a-brief-talk-about-immutability-and-react-s-helpers-70919ab8ae7c).

**Comment by doctorpiorno** [comment]
Thanks! This is very interesting and not something I was terribly aware of — I think my use of concat and filter was a bit of a happy coincidence. Will take a look at the suggested reading materials.
