### ISSUE TITLE
Saving playlists to account

### ISSUE THREAD

**Issue by ghost** [doctorpiorno/jammming#5]
https://github.com/doctorpiorno/jammming/blob/master/src/Components/App/App.js#L38-L41

You really only need `track.uri`. You don't need to prefix anything to the string.

You could also do this on a single line using `.map()`:

```javascript
let trackURIs = this.state.playlistTracks.map(track => track.uri);
```

https://github.com/doctorpiorno/jammming/blob/master/src/Components/App/App.js#L44-L45

You only need a single call to `this.setState`. Just pass both properties that need to be updated to the state object:

```javascript
this.setState({
  playlistTracks: [],
  playlistName: "New Playlist"
});
```

https://github.com/doctorpiorno/jammming/blob/master/src/Components/Playlist/Playlist.js#L20

Use `value` attribute instead of `defaultValue` and give the attribute a value of `{ this.props.playlistName }` so that your form input updates after you save the playlist.

Besides that, recall that `Spotify.savePlaylist()` returns a `Promise`, so you should use `.then()` to ensure that the `Playlist`'s state is cleared _after_ the playlist has been created and its tracks have been added to it.

**Comment by doctorpiorno** [comment]
Thanks for the feedback! Took me a bit to "get" your suggestion to use `map()`, but I managed it in the end. I still need to read up on the documentation re: `value` VS `defaultValue` — I'm still somewhat unclear on what the difference between the two is exactly, although one of them clearly works while the other does not. 🤷‍♂️ 

Thanks for the tip about the promise in `Spotify.savePlaylist()`. It took me a bit to figure it out but it's now working and a lot more robust.
